[workspace]
members = [
    "console-app",
    "server-app",
    "parser",
]
resolver = "2"

[workspace.dependencies]
serde = { version = "1.0", features = ["derive"] }
serde-big-array = "0.4"
serde_json = "1.0"