[package]
name = "console-app"
version = "0.1.0"
edition = "2021"

[dependencies]
parser = { path = "../parser" }

serde_json.workspace = true
serde.workspace = true
serde-big-array.workspace = true

clap = { version = "4.5.23", features = ["derive"] }
